config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get  '/admin/:id', to: 'users#admin', as: 'admin'
  get  'auth/:provider/callback', to: 'sessions#create'
  get  'auth/failure', to: redirect('/')
  get  'signout', to: 'sessions#destroy', as: 'signout'
  get  'cds/fav/:id' => 'cds#fav', as: 'fav_cds'
  get  'cds/op_cd/:id' =>  'cds#op_cd', as:'op_cd'
  get  'cds/edit/:id'  =>  'users#edit', as: 'edit_user'
  post '/st_up',  to: 'users#st_up'

  resources :cds,      only: %i(create update destroy)
  resources :users,    only: %i(show create update destroy)
  resources :sessions, only: %i(create destroy)

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cd.rb
class Cd < ApplicationRecord

  belongs_to :user
  has_many :musics, dependent: :destroy, inverse_of: :cd
  has_many :favorites, dependent: :destroy
  accepts_nested_attributes_for :musics, allow_destroy: true
  attachment :cd_image

  validates :cd_title, presence: true, length: { maximum:20 }
  validates :cd_genre, presence: true, length: { maximum:20 }

  def favorited_by?(user) #いいねしているかどうか
    favorites.where(user_id: user.id).exists?
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :cd
  
end

app/models/music.rb
class Music < ApplicationRecord

  belongs_to :cd
  has_one_attached :audio

  validates :music_title, presence: true, length: { maximum:20 }
  
end

app/models/user.rb
class User < ApplicationRecord

  enum status: {gest: 0,contribution: 1,unsubscribe: 2}
  has_many :cds, dependent: :destroy
  has_many :load_music, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :image

  validates :introduction, length: {maximum: 200}

  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
     user.provider = auth.provider
     user.uid = auth.uid
     user.name = auth.info.name
     user.email = auth.info.email
     user.user_image = auth.info.image
     user.oauth_token = auth.credentials.token
     user.oauth_expires_at = Time.at(auth.credentials.expires_at)
     return user
   end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 helper_method :current_user, :signed_in?

 def current_user
   User.find(session[:user_id]) if session[:user_id]
 end

 def signed_in?
    current_user
 end

 def oauth_failure
    flash[:notice] = "Canceled."
    redirect_to "/"
 end

end

app/controllers/cds_controller.rb
class CdsController < ApplicationController

  def create
    cd = Cd.new(cd_params)
    cd.user_id = current_user.id
    cd_a = cd.musics.map{|a| a.audio.attached?}
    if cd_a.any? {|w| w == false } || cd_a.blank?
      redirect_to user_path(current_user.id),notice: "ERROR! You can't do it."
    else
      if cd.save
        redirect_to user_path(current_user.id),notice: "Successfully Save."
      else
        redirect_to user_path(current_user.id),notice: "ERROR! You can't do it."
      end
    end
  end

  def update
    @cd = Cd.find(params[:id])
    if @cd.user_id != current_user.id
      redirect_to root_path
    else
      if @cd.update(cd_params)
        cd_a = @cd.musics.map{|a| a.audio.attached?}
        if cd_a.any? {|w| w == false } || cd_a.blank?
          redirect_to edit_user_path(@cd.id),notice: "ERROR! You can't do it."
        else
          redirect_to user_path(current_user.id),notice: "Successfully Save."
        end
      else
        redirect_to  edit_user_path(@cd.id),notice: "ERROR! You can't do it."
      end
    end
  end

  def destroy
    cd = Cd.find(params[:id])
    cd.destroy
    flash.now[:notice] = " Successfully Delete."
    redirect_to user_path(current_user.id),notice: "Successfully Save."
  end

  def fav
    cd = Cd.find(params[:id])
    if cd.favorited_by?(current_user)
      fav = current_user.favorites.find_by(cd_id: cd.id)
      fav.destroy
      ct_user = current_user
      render partial: 'partial/favorites', locals: {:ct_user => ct_user}
    else
      fav = current_user.favorites.new(cd_id: cd.id)
      fav.save
      ct_user = current_user
      render partial: 'partial/favorites', locals: {:ct_user => ct_user}
    end
  end

  def op_cd
    cd = Cd.find(params[:id])
    render partial: 'partial/cd.show', locals: { :cd => cd }
  end

  private

  def cd_params
    params.require(:cd).permit(:user_id,:cd_title, :cd_image, :cd_genre, musics_attributes: [:id, :cd_id, :audio, :music_title, :_destroy])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    if current_user
      @user  = current_user
    end
    @users = User.all
    @cds   = Cd.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.status != "unsubscribe"
      if user.save
        session[:user_id] = user.id
        redirect_to root_path
      else
        redirect_to root_path,notice: "ERROR! You can't do it."
      end
    else
      redirect_to root_path,notice: "ERROR! You can't do it."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path,notice: "Good Bye"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: :update
  protect_from_forgery except: :image_update

  def qr_code #QRコード作成メソッド
    @qr = RQRCode::QRCode.new(url_for :controller => 'users', :action => 'show', :only_path => false, :size => 8, :level => :h ).as_svg.html_safe
  end

  def show #ユーザ詳細画面
    @user = User.find(params[:id])
    qr_code
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "sample",   # PDF名
        template: "partial/_qr_code.html.erb" # viewを対象にする
      end
    end

    @cds = Cd.all
    @cd  = Cd.new

  end

  def admin #管理者画面
    if ENV['EMAIL']!= current_user.email
      redirect_to root_path
    end
    @users  = User.page(params[:page]).reverse_order
     if params[:content] == ""
       @users = User.page(params[:page]).reverse_order
     else
       users = User.where('name LIKE ?', "%#{params[:content]}%").or(User.where('nick_name LIKE ?', "%#{params[:content]}%"))
       if users == []
         flash.now[:danger] = "ERROR! You can't do it."
       end
       users_id = []
       users.each do |f|
         users_id.push(User.find(f.id))
       end
       @users = Kaminari.paginate_array(users_id).page(params[:page])
     end
  end

  def edit
    @cd = Cd.find(params[:id])
    if @cd.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update #更新アクション
    if current_user.update(user_params)
      if current_user.status == "gest"
        redirect_to  root_path(current_user),notice: "Successfully Save."
      else
        redirect_to  user_path(current_user),notice: "Successfully Save."
      end
    else
      if current_user.status == "gest"
        redirect_to  root_path(current_user),notice: "ERROR! You can't do it."
      else
        redirect_to  user_path(current_user),notice: "ERROR! You can't do it."
      end
    end
  end

  def st_up  #status変更
    if current_user.status == "gest"
      user = User.find(current_user.id)
      user.status = "contribution"
      user.save
      redirect_to user_path(current_user),notice: "Welcome To Contribuiton."
    end
  end

  def destroy #削除アクション
    user = User.find(params[:id])
    user.status = "unsubscribe"
    user.save
    if current_user.email == ENV['EMAIL']
      redirect_to admin_path(current_user),notice: "Good Bye"
    else
      session[:user_id] = nil
      redirect_to root_path,notice: "Good Bye"
    end
  end

  private #ストロングパラメータ

  def user_params
    params.require(:user).permit(:nick_name,:image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_header.html.erb
<% c_user = current_user %>
<div class="container-fruid header" >
  <div id="sp-menu">
    <div class="wrap">
    <% if c_user %>
        <%= render "users/user_hm" %>
    <% else %>
      <%= render "partial/sign_in" %>
    <% end %>
    </div>
  </div>
</div>
<div>
  <h2 >
   <%= link_to "L i G a t e", root_path, id: "hm-logo" %>
  </h2>
  <div id="hm-icon">
    <%= link_to "C o n t a c t  U s", ENV['OTOIAWASE'], :target=>["_blank"], class: "hm-li"%>
    <%= link_to "", class: "menu-trigger"  do %>
      <span></span><span></span><span></span>
    <% end %>
  </div>
</div>

<script type="text/javascript">
$(function() {
  $('.menu-trigger').on('click', function() {
    $(this).toggleClass('active');
    $('#sp-menu').fadeToggle();
    return false;
  });
});
</script>

<style type="text/css">
#hm-logo{
position: fixed;
left: 22px;
top: 22px;
z-index: 10;
font-size: 45px;
font-family: 'Comic Sans MS';
color: black;
}



#hm-logo:hover{
  opacity: 0.5;
  color: black;
  text-decoration:none;
}

#hm-icon{
position: fixed;
right: 30px;
top: 25px;
z-index: 10;
}


.header{
  height: 100px;
}

.hm-li{
  color: black;
  padding-right: 30px;
  font-size: 40px;
  font-family: 'Comic Sans MS';
  text-decoration:none;
}

.hm-li:hover{
  color: black;
  opacity: 0.5;
  text-decoration: none;
}

.wrap{
  width: 90%;
  max-width: 800px;
  margin: 100px auto;
}

.menu-trigger,.menu-trigger span {
display: inline-block;
transition: all .4s;
box-sizing: border-box;
}

.menu-trigger {
position: relative;
width: 50px;
height: 44px;
}

.menu-trigger span {
position: absolute;
left: 0;
width: 100%;
height: 4px;
background-color: #000;
border-radius: 4px;
}

.menu-trigger span:nth-of-type(1) {
top: 0;
}

.menu-trigger span:nth-of-type(2) {
top: 20px;
}

.menu-trigger span:nth-of-type(3) {
bottom: 0;
}

.menu-trigger.active span:nth-of-type(1) {
-webkit-transform: translateY(20px) rotate(-45deg);
transform: translateY(20px) rotate(-45deg);
background-color: #fff;
}

.menu-trigger.active span:nth-of-type(2) {
opacity: 0;
}

.menu-trigger.active span:nth-of-type(3) {
-webkit-transform: translateY(-20px) rotate(45deg);
transform: translateY(-20px) rotate(45deg);
background-color: #fff;
}

/* ------ spメニュー ------ */

#sp-menu {
position: fixed;
top: 0;
left: 0;
background: rgba(0,0,0,0.7);
color: #fff;
width: 100%;
min-height: 100%;
display: none;
z-index: 9;
}

#sp-menu li{
text-align: center;
margin-bottom: 30px;
}

</style>

app/views/homes/top.html.erb
<% c_user = current_user %>
<div id="top">
  <h1>Welcome to</h1>
  <h2>LiGate</h2>
  <% if !c_user %>
    <%= link_to "→Sign in ?", "/auth/google_oauth2", class: "btn btn-outline-dark"%>
  <% else %>
    <% if c_user.nick_name != "NickName" %>
      <h3><%= c_user.nick_name %>!!<h3>
    <% else %>
      <h3><%= c_user.name %>!!<h3>
    <% end %>
  <% end %>
  <h5 class="flash_m">　<%= flash.now[:notice] %></h5>
</div>
<div class="cd_list">
  <h1>CD List</h1>
  <div class="slider1" >
    <ul class="horizontal-list">
      <% @cds.each do |f| %>
        <%= link_to user_path(f.user.id) do %>
          <li class="item">
            <%= attachment_image_tag  f, :cd_image, format: 'jpeg', fallback: "/audio.no_image.jpg", size: "350x350", class: "item_image1" %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="user_list">
  <h1>User List</h1>
  <div class="slider2 header_list">
    <ul class="horizontal-list">
      <% @users.each do |f| %>
        <% if f.status == "contribution" %>
        <li class="item">
          <%= link_to user_path(f.id) do %>
            <%if f.image_id == nil %>
              <%= image_tag(f.user_image,  :size => "350x350", class: "item_image2") %>
            <% else%>
              <%= attachment_image_tag  f, :image, format: 'jpeg', size: "350x350", class: "item_image2" %>
            <% end %>
          <% end %>
        </li>
        <% end %>
     <% end %>
    </ul>
  </div>
</div>

<style type="text/css">
 #top{
   height: 600px;
   width: 100%;
   z-index: 1;
   background-image: url("/header.jpg");
   background-repeat: no-repeat;
   background-position: center;
   background-size: cover;
 }
 #top h1{
   position: absolute;
   font-size: 50px;
   right: 230px;
   top:120px;
   font-family: 'Comic Sans MS';
   z-index: 2;
 }
 #top h2{
   position: absolute;
   font-size: 50px;
   right: 180px;
   top:190px;
   font-family: 'Comic Sans MS';
   z-index: 2;
 }

 #top h3{
   position: absolute;
   color: black;
   font-size:40px;
   font-weight: 1;
   right: 100px;
   top:260px;
   font-family: 'Comic Sans MS';
   z-index: 2;
 }
 #top a{
   position: absolute;
   font-size:40px;
   font-weight: 1;
   right: 50px;
   top:260px;
   font-family: 'Comic Sans MS';
   z-index: 2;
 }

 #top a:hover{
   text-decoration: none;
 }


 .cd_list {
   border-top: 6px solid rgba(0,0,0,0.5);
   border-bottom: 6px solid rgba(0,0,0,0.5);
 }
 .user_list{
   border-bottom: 6px solid rgba(0,0,0,0.5);
 }

 .cd_list h1, .user_list h1{
   text-align: left;
   margin-left: 10px;
   font-size: 75px;
   font-family: 'Comic Sans MS';
 }



.slider1, .slider2 {
  overflow-x: auto;
  white-space: nowrap;
  -webkit-overflow-scrolling: touch;
  margin-bottom: 20px;
}
.item {
  /* 横スクロール用 */
  display: inline-block;
  width: 350px;
  /* 見た目調整 */
  height: 350px;
  margin: 16px;
  font-size: 48px;
}

.item_image1{
    border: 10px solid #FFDBC9;
    border-radius: 100px;
}

.item_image2{
    border: 10px solid #000055;
    border-radius: 175px;
}

.flash_m{
  position: absolute;
  left:0;
  top:100px;
}


</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ligate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: rgba(0,0,0,0);">
    <% c_user = current_user %>
    <header class="fixed-top">
      <%= render "homes/header" %>
    </header>
    <div class="contents">
      <%= yield %>
    </div>

  </body>

</html>

<style type="text/css">

.contents{
  margin-bottom: 100px;
}
</style>

app/views/partial/_cd.show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content" >
    <div class="cd_show">

      <div class="row">
        <div class="col-6">
          <%= attachment_image_tag  cd, :cd_image, format: 'jpeg',fallback: "/audio.no_image.jpg", size: "200x200", class: "player_image"%>
        </div>
        <div class="col-6 play-int">
          <h4>Title:<%= cd.cd_title %></h4>
          <h4>Genre:<%= cd.cd_genre %></h4>
        </div>
      </div>

      <div class="row" style="text-align: center; margin-top: 50px;">
        <div class="col-12">
          <ol id="Audio-Control">
            <% cd.musics.each do |a| %>
              <li style="margin: 10px;">
                <div class="row" >
                  <div class="col-6">
                  <p ><%= a.music_title %></p>
                  </div>
                  <div class="col-6 audio-player" >
                    <audio src="<%= url_for(a.audio) %>"></audio>
                    <button type="button" class="btn btn-primary on">ON</button>
                    <button type="button" class="btn btn-primary off">OFF</button>
                  </div>
                </div>
              </li>
            <% end %>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

$(document).on('click', '.on',function(){
     $('#Audio-Control audio').each(function(index, el){
       el.pause()
       el.currentTime = 0;
     })
     $('#Audio-Control p').each(function(index, el){
       $(el).css('background', '');
     })
     $(this).prevAll("audio").get(0).play();
     $(this).parent().parent().find("p").css('background', 'rgba(51,153,255,0.5)');
});

$(document).on('click', '.off',function(){
  $(this).prevAll("audio").get(0).pause();
  $(this).parent().parent().find("p").css('background', '');
});




</script>

<style type="text/css">

.audio-player{
  text-align :right;
}

.cd_show{
  margin: 30px;
}

.player_image{
  border-radius: 30px;
}

.play-int{
  margin-top: 130px;
}
li{
   text-align: left;
   color:black;
  font-size: 30px;
}

</style>

app/views/users/_user_hm.html.erb
<% c_user = current_user %>
<ul id="tab-menu" class="clearfix" style="border-radius: 100px;">
  <li ><a name="#tab1" class="active btn">Profile</a></li>
  <li><a name="#tab2" class="btn">Favorite CB</a></li>
  <li>
    <% if  c_user.email == ENV['EMAIL'] %>
      <%= link_to "Admin", admin_path(c_user) %>
    <% elsif  c_user.status == "contribution"  %>
      <%= link_to "Contributor", user_path(c_user) , class: "btn"%>
    <% else  %>
      <%= link_to "Become CB?",st_up_path(c_user), "data-confirm" => "投稿者になりますか？", method: :post, class: "btn"  %>
    <% end %>
  </li>
  <li><%= link_to "Sign out", signout_path, id: "sign_out", class:"btn" %></li>
</ul>

<div id="tab-contents" class="clearfix">
  <div id="tab1" class="tab"><%= render "users/profile" %></div>
  <div id="tab2" class="tab"><%= render "partial/cds" %></div>
</div>

<style type="text/css">
.clearfix:after{
  content:"";
  clear: both;
  display: block;
}
#tab-menu{
  padding: 0;

}
#tab-menu li {
  float: left;
  list-style-type: none;
  width: 25%;

}

#tab-menu a {
  color: #fff;
  text-decoration: none;
  display: block;
  padding: 20px;
  text-align: center;
  background: #000;
  border: 1px solid #000;
  border-bottom: none;
}

#tab-menu .active {
  background: #fff;
  color: #000;
}

#tab-contents .tab {
  padding: 30px;
  background: #fff;
  border: 1px solid #000;
  border-top: none;
  border-radius: 100px;
}

#tab-contents p{
  color:#000;
  line-height: 2.5;
}
</style>

<script type="text/javascript">
$('#tab-contents .tab[id != "tab1"]').hide();

$('#tab-menu a').on('click', function() {
  $("#tab-contents .tab").hide();
  $("#tab-menu .active").removeClass("active");
  $(this).addClass("active");
  if ($(this).attr("name")) {
  $($(this).attr("name")).show();
  return false;
}});

</script>

app/views/users/show.html.erb
<% c_user = current_user %>
<div id="top"></div>
<div class=" container" style="margin: 50px auto 80px auto ;">
  <h5 class="flash_m"><%= flash.now[:notice] %></h5>
  <div class="row">
    <div class="col-5  image" style="text-align: center;" >
      <%if @user.image_id == nil %>
        <%= image_tag(@user.user_image,  :size => "300x300", class:"image") %>
      <% else%>
        <%= attachment_image_tag  @user, :image, format: 'jpeg', size:"300x300" , class:"image"%>
      <% end %>
    </div>
    <div class="col-7 name" style="padding-left: 25px;">
      <div class="row">
        <div class="col-5">
          <h2>CB:<%= @user.nick_name %></h2>
        </div>
        <div class="col-7" style="text-align: right; padding-right: 33px;">
          <%= link_to "PDF", "http://localhost:3000/users/#{@user.id}.pdf",:target=>["_blank"],  class: "btn btn-primary", style:" width: 73px;"%>
          <button type="button" class="btn btn-primary " id="button1" style="width: 77px;">QR</button><br>
          <% if  c_user  && c_user.status == "contribution" && c_user.id == @user.id %>
            <button type="button" class="btn btn-primary " id="button3" style="margin-top: 10px; width: 73px;">Introd</button>
            <button type="button" class="btn btn-primary " id="button2" style="margin-top: 10px;">AddCD</button>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12"><h1>Introduction:</h1></div>
      </div>
      <div class="row">
        <div class="col-11" style="height: 100%;  border: 1px solid black; margin-left: 3%;">
          <% if @user.introduction.empty? %>
            <h4>
              Welome to contributor!!<br>
              Please add a Introduction<br>
            </h4>
          <% else%>
            <h4><%= simple_format(@user.introduction) %><h4>
          <% end %>
        </div>
        <div class="colo-1"></div>
      </div>
    </div>
  </div>
</div>

<div class="container" >
  <div class="row">
    <div class="col-12">
      <h1 class="cd_list">CD List</h1>
      <ul class="slider">
        <% @user.cds.each do |f| %>

        <li class="item">
          <div style="position: relative;">
          <% if c_user %>
            <% if f.favorited_by?(c_user) %>
              <%= link_to fav_cds_path(f), class: "fav", remote: true do %>
                <i class="fas fa-heart" ></i>
              <% end %>
            <% else %>
              <%= link_to fav_cds_path(f), class: "fav", remote: true do %>
                <i class="far fa-heart" ></i>
              <% end %>
            <% end %>
          <% end %>
          <% if  c_user  && c_user.status == "contribution" && c_user.id == @user.id %>
            <%= link_to "Che", edit_user_path(f), class: "btn btn-primary ch_cd"%>
            <%= link_to "Del", cd_path(f.id), method: :delete,"data-confirm" => "Do you really want to delete this？", class: "btn btn-danger ch_de" %>
          <% end%>
          <p class="cd_title"><%= f.cd_title%></p>
          <%= link_to op_cd_path(f),id:"op", remote: true do %>
            <%= attachment_image_tag  f, :cd_image, format: 'jpeg',fallback: "/audio.no_image.jpg", size: "250x250", id: "#{f.id}", class: "item_image"%>
          <% end %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="modal fade" id= "cd_show">
  <div class="modal-dialog" role="document">
    <div class="modal-content" >
      <h3>Select_CD</h3>
    </div>
  </div>
</div>

<div class="modal fade" id="dialog1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= render "partial/qr_code" %>
    </div>
  </div>
</div>

<div class="modal fade" id="dialog2">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="add_music">
        <%= form_with(model: @cd, local: true)  do |f| %>
          　<%= f.label :cd_image,style: "margin-right:3px;" %>    ：<%= f.attachment_field  :cd_image %><br>
          　<%= f.label :cd_title ,style: "margin-right:3px;"%>　  ：<%= f.text_field :cd_title, :placeholder => "CD titile" %><br>
          　<%= f.label :cd_genre,style: "margin-right:4px;" %>    ：<%= f.text_field :cd_genre, :placeholder => "CD genre"%><br>
          <div>
            <%= f.fields_for :musics do |i| %>
              <%= render 'music_fields', f: i %>
            <% end %>
           　<%= link_to_add_association '+Audio',f, :musics, class: "btn btn-outline-secondary"  %>
          </div>
          <%= f.submit "Create" , style: "margin-left:370px; width: 83px" , "data-confirm" => "全て入力した？",class: "btn btn-outline-secondary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="dialog3">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="text-align: center;">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= f.label :introduction%><br />
        <%= f.text_area :introduction, :placeholder => "Introduction", style:"color: black; width: 80%; height: 150px;" %><br />
        <%= f.submit 'Contribution',style: "margin-left: 280px; ","data-confirm" => "入力内容は大丈夫？",class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
$('#button1').on('click', function() {
    $('#dialog1').modal();
});

$('#button2').on('click', function() {
    $('#dialog2').modal();
});

$('#button3').on('click', function() {
    $('#dialog3').modal();
});

$('#button4').on('click', function() {
    $('#dialog4').modal();
});

$('.fav i').each(function(a){
  $(this).attr('id','fav_' + (a+1));
});

$(".fav i").each(function (a) {
  a = a+1;
  $('#fav_' + a ).click(function() {
    if ($("#fav_"+ a).hasClass('fas')) {
      $("#fav_"+ a).removeClass('fas').addClass('far');
    } else {
      $("#fav_"+ a).removeClass('far').addClass('fas');
    }
  });
});

$(function(){
  $(document).on("ajax:success","#op",function(e){
    data = e.detail[0]
    $("#cd_show").html(e.detail[2]['response']).modal();
  })
})
</script>

<style type="text/css">

#top{
  height: 300px;
  width: 100%;
  z-index: 1;
  background-image: url("/show.header1.jpg");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}
.container{
  margin-top: 100px;
}
.fa-heart {
    color: red;
  }
.slider{
  overflow-x: auto;
  white-space: nowrap;
  -webkit-overflow-scrolling: touch;
  margin-bottom: 20px;
  border-top: 3px solid rgba(0,0,0,0.5);
  border-bottom: 3px solid rgba(0,0,0,0.5);
}
.item {
  /* 横スクロール用 */
  display: inline-block;
  width: 250px;
  /* 見た目調整 */
  height: 250px;
  margin: 16px;
  font-size: 48px;
}

.item_image{

  border: 10px solid rgba(0, 0, 0, 0.4);
  border-radius: 25px;
}
.image{
  border-radius: 150px;
}

.fav{
  position: absolute;
  z-index: 2;
  left: 10px;
}

#op{
  z-index: 1;
}

.add_music{
  padding:20px;
}

.add_music a{
  color: black;
}

.add_music a:hover{
  opacity: 0.5;
  text-decoration: none;
}

.ch_cd{
  position: absolute;
  bottom: 0;
  right: 50px;
}
.ch_de{
  position: absolute;
  bottom: 0;
  right:  0;
}
.cd_title{
  font-size:5px;
  background-color: rgba(255,255,255,0.8);
  position: absolute;
  bottom: 0;
  left: 15px;
  border-radius: 5px;
}

.flash_m{
  position: absolute;
  top: 275px;
  left:  0px;
}

.cd_list {
  text-align: left;
  margin-left: 10px;
  font-size: 75px;
  font-family: 'Comic Sans MS';
}

</style>